### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wyattscarpenter** [stuartlangridge/unsong-book-fetcher#4]
I'd like to adapt this project for some other things, so I'm wondering if you'd be willing to release it under a free software license. My personal preference would be CC0, but it's your project.

**Comment by wyattscarpenter** [comment]
👋 Hello again! I'm wondering if you'd be willing to add a CC0 license to this code so I can be more assured of my legal ability to reuse it (as I intend to do, one of these days).

**Comment by wyattscarpenter** [comment]
There's a convenient way to do it, described here https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository but I can't do it that convenient way in a pull request unfortunately.

**Comment by stuartlangridge** [comment]
Licensed under CC0 as requested!

**Comment by wyattscarpenter** [comment]
Awesome, thanks!
